spring.application.name=MealPlan

spring.datasource.url=jdbc:mysql://localhost:3306/mealplanner?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
<<<<<<< HEAD
spring.datasource.username=user
=======
spring.datasource.username=root
>>>>>>> af4720bcfe3a028f96309e1ded12c039dc4cae68
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
